server:
  port: 8077

spring:
  servlet:
    multipart:
      max-file-size: 1024MB #最大上传单个文件大小：默认1M,现在是1G
      max-request-size: 1024MB # 最大置总上传的数据大小 ：默认10M,现在是1G
      enabled: true

dockertest:
#  linuxPath: "D:/HD/"
  linuxPath: "/root/dockerfiledome/"